version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app

  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - shopping-app-data:/data/db

volumes:
  shopping-app-data: